### ISSUE TITLE
cpu percent not showing up

### ISSUE THREAD

**Issue by albertmichaelj** [jupyter-server/jupyter-resource-usage#143]
## Description

I am using the latest release of `jupyter-resource-usage`, and I have enabled `c.ResourceUseDisplay.track_cpu_percent=true` in my jupyter server config file. However, the CPU usage does not show up in the status bar. I am using JupyterLab 3.4.6, and I have the environmental variable `CPU_LIMIT=2.0`. My backend is Jupyter Server, not notebook. My understanding is that since release 0.6.1, this should show the CPU usage in the status bar besides the memory usage.

I have also tried launching the notebook with the `--ResourceUseDisplay.track_cpu_percent=True` command line flag, and there is no difference.

Is there something that I'm missing, or is this a bug with a newer version of Jupyter Lab?

Thank you.

## Context

- Operating System and version: Linux (in a docker container) kernel 5.4, base container is ubuntu:22.04
- Browser and version: Chrome 105
- Jupyter Server version: 1.18.1

**Comment by albertmichaelj** [comment]
Ah, I misunderstood. I thought that it was supposed to show in the lab interface as well.

I have tried `jupyterlab-system-monitor`, but one of the issues I have with it is that it shows the memory usage in two places. Once in the top bar (like it is supposed to), and the other in the bottom status bar. The bottom display is actually directly from this extension, and it seems to be automatically enabled whenever `jupyter-resource-usage` is installed (which is a dependency of `jupyterlab-system-monitor`). So, I end up with the memory usage display twice, and there does not seem to be a way to disable the memory display in `jupyter-resource-usage`. Is there a way to directly disable the memory usage display for `jupyter-resource-usage` and just keep the metrics api so that `jupyterlab-system-monitor` can pull the data that it needs? As far as I can tell, there is no configurable to do this, but I could have missed something.

Feel free to close this issue as it seems to be a misunderstanding on what functionality is already in the extension.

**Comment by jtpio** [comment]
> there does not seem to be a way to disable the memory display in `jupyter-resource-usage`

The plugin can be disabled with `jupyter labextension disable @jupyter-server/resource-usage:memory-status-item`.

Also there is an issue to track adding CPU usage to the JupyterLab extension: https://github.com/jupyter-server/jupyter-resource-usage/issues/84. So maybe we can close this issue in favor of https://github.com/jupyter-server/jupyter-resource-usage/issues/84 and continue the conversation there?

**Comment by albertmichaelj** [comment]
That disable command worked perfectly. Thanks for following up with that. I'm happy to close this in favor of #84. Thanks for your help!
