### ISSUE TITLE
Incorrect dependency version requirement on `jupyter_server`

### ISSUE THREAD

**Issue by vikramaditya91** [jupyter-server/jupyter-resource-usage#169]
## Description

`jupyter-resource-usage` demands that the version of `jupyter_server` is less than 2.
This is incorrect, and I suspect it is cached somewhere.

## Reproduce

`conda search jupyter-resource-usage` will output

```
jupyter-resource-usage 0.7.0 pyhd8ed1ab_0
-----------------------------------------
file name   : jupyter-resource-usage-0.7.0-pyhd8ed1ab_0.conda
name        : jupyter-resource-usage
version     : 0.7.0
build string: pyhd8ed1ab_0
build number: 0
channel     : https://conda.anaconda.org/conda-forge/noarch
size        : 34 KB
arch        : None
constrains  : ()
license     : BSD-3-Clause
license_family: BSD
md5         : c57567d49d926826b1f852712ac8acfa
noarch      : python
package_type: noarch_python
platform    : None
sha256      : c0dc8adf261c86b8adad79546e9acbe07c9a6e4482bf6819a8821b02c26e1409
subdir      : noarch
timestamp   : 1673012131916
url         : https://conda.anaconda.org/conda-forge/noarch/jupyter-resource-usage-0.7.0-pyhd8ed1ab_0.conda
dependencies:
    jupyter_server >=1.0.0,<2
    psutil
    python >=3.6
```

I expect the `jupyter_server` requirement to be  `jupyter_server >=1.0.0,<3`

I would like to make a PR, but I am not sure where the version `<2` is coming from.

**Comment by jtpio** [comment]
Thanks @vikramaditya91 for the report.

It's probably coming from there: https://github.com/conda-forge/jupyter-resource-usage-feedstock/blob/b9b8e14cd54a34865e3416c5b7d440b317e7dd74/recipe/meta.yaml#L23

If you want to open a PR on that repo that would be great, thanks!

**Comment by vikramaditya91** [comment]
Thanks for the heads-up @jtpio .
Made a PR there

**Comment by jtpio** [comment]
> What is the convention when we are only bumping the `conda` specific metadata? to keep the same version or bump the version?

In that case we can bump the `build` number.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/conda-forge/jupyter-resource-usage-feedstock/pull/9
