### ISSUE TITLE
Reporting Disk Usage 

### ISSUE THREAD

**Issue by laufers** [jupyter-server/jupyter-resource-usage#186]
### Problem
* I would like it, similar to cpu and memory usage, we could display disk usage to alert users that the local storage (/home/user) is approaching capacity. 

### Proposed Solution
* Display disk usage similar to cpu and memory

**Comment by ryanlovett** [comment]
It would also be valuable to report disk utilization for volumes besides the user's home directory.

**Comment by iandesj** [comment]
> It would also be valuable to report disk utilization for volumes besides the user's home directory.

I agree. I think #233 would be a solid starting point though.

**Comment by perllaghu** [comment]
See https://github.com/jupyter-server/jupyter-resource-usage/pull/233

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter-server/jupyter-resource-usage/pull/233.
