### ISSUE TITLE
Implement JupyterLab dark theme

### ISSUE THREAD

**Issue by ryanhill1** [jupyter-server/jupyter-resource-usage#192]
### Problem

Right now, switching **Appearance** > **Themes** > **JupyterLab Dark** has no effect. The kernel usage sidebar content is still displayed with white backdrop.

<img width="1405" alt="Screenshot 2023-05-02 at 1 38 11 PM" src="https://user-images.githubusercontent.com/46977852/235756842-f51b791b-8902-4d8f-8a85-3301572030d9.png">

### Proposed Solution

Change the kernel usage text and backdrop to use the Jupyter theme colors CSS so that the light/dark theme switch is recognized

### Additional context

For example, Debugger extension sidebar light/dark theme switch:

<img width="1486" alt="Screenshot 2023-05-02 at 1 40 10 PM" src="https://user-images.githubusercontent.com/46977852/235757135-4fd854f0-5372-490b-9ac5-419f0eabbe75.png">

Many of the built-in jupyter extensions, such as this one, can likely be used as reference

**Comment by jtpio** [comment]
Thanks @ryanhill1 for reporting.

I believe this should be fixed in `0.7.2`?

![image](https://github.com/jupyter-server/jupyter-resource-usage/assets/591645/fcf24b9a-24d5-417d-81b3-06ce927b9989)

**Comment by ryanhill1** [comment]
@jtpio Yep, all good on my end too. Looks awesome, thanks!

<img width="1465" alt="Screenshot 2023-06-29 at 9 56 59 PM" src="https://github.com/jupyter-server/jupyter-resource-usage/assets/46977852/b9bea273-23f4-414b-9cd7-4d25cac6a4b6">
