### ISSUE TITLE
Update the documentation in `README.md`

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter-resource-usage#203]
Follow-up to https://github.com/jupyter-server/jupyter-resource-usage/pull/202

We should update the `README.md` to better reflect the current state of the extension to be released in `1.0.0`:

- JupyterLab 4 support
- Notebook 7 support
- status bar and top bar components
- Tell users to use NBClassic if they still want the classic notebook UI

**Comment by mahendrapaipuri** [comment]
Yes, I was doing that and I wanted to push the commits today. Sorry, I should have put #202 as WIP. Anyways, I am already on it and I will open up a PR today!

**Comment by jtpio** [comment]
No problem, thanks for working on this!

**Comment by mahendrapaipuri** [comment]
@jtpio Btw, forgot to link this issue in PR. This is done in #205. We can close it now!

**Comment by jtpio** [comment]
Nice thanks @mahendrapaipuri!
