### ISSUE TITLE
Notebook 7: kernel usage is missing

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter-resource-usage#204]
## Description

With Notebook 7 the side panel shows "Kernel usage is missing".

## Reproduce

1. Open a new Notebook with Notebook 7
2. Open the kernel usage side panel

![image](https://github.com/jupyter-server/jupyter-resource-usage/assets/591645/4a6d195f-079b-464f-beb1-177672be7b1a)

## Expected behavior

It should show kernel metrics like in JupyterLab:

![image](https://github.com/jupyter-server/jupyter-resource-usage/assets/591645/310bf523-a734-4a33-921d-7c2d6169c8f6)

## Context

- Notebook 7.0.0
- `jupyter-resource-usage` main branch

**Comment by jtpio** [comment]
cc @mahendrapaipuri if you are interested in taking a look maybe.

Looks like this is the last remaining issue before being able to make a `1.0.0` release that would be compatible with JupyterLab 4 and Notebook 7.

**Comment by mahendrapaipuri** [comment]
Yes, I will have a look at it! Cheers!

**Comment by jtpio** [comment]
Thanks!

**Comment by mahendrapaipuri** [comment]
@jtpio I tried to look into it a bit yesterday but I am afraid that I am bit out of my depth here. 

In the case of notebook interface, seems like the [subscription](https://github.com/jupyter-server/jupyter-resource-usage/blob/dd0ce33ddb0cca8bb7e784c6aaf63f7d18785ad2/packages/labextension/src/widget.tsx#L237) here is not behaving as it should. The tracker is emitting the active kernel and connection to the slot `notebookChangeCallback` returns `true` as well. But, the callback `notebookChangeCallback` never gets executed. So, all the react hooks stay in `undefined` state. 

Do you know where should I look into?

**Comment by jtpio** [comment]
Thanks for looking into it :+1: 

This is strange, normally it should indeed react to the `currentChanged` signal of the notebook tracker (used in the Notebook 7 code base). Maybe it's an issue with the lifecycle of the component (registering the callbacks too late maybe).

**Comment by jtpio** [comment]
I think https://github.com/jupyter-server/jupyter-resource-usage/pull/206 should fix it.
