### ISSUE TITLE
I want to display the cpu usage on the screen.

### ISSUE THREAD

**Issue by asdf0480** [jupyter-server/jupyter-resource-usage#67]
![캡처](https://user-images.githubusercontent.com/54887406/96943696-d2323600-1513-11eb-964e-dee5f199c48c.JPG)
Can you tell me how to pull out the cpu_percent in this part? I want to express it in the main.js.

**Comment by jtpio** [comment]
@asdf0480 it can be enabled via the config or the command line, for example:

```bash
jupyter notebook --NotebookApp.ResourceUseDisplay.track_cpu_percent=True --NotebookApp.ResourceUseDisplay.cpu_limit=2
```

Then the value should appear in the `/metrics` response. When running locally: http://localhost:8888/metrics

**Comment by KahThong** [comment]
May I know if it is possible to get cpu usage display on the notebook right top corner?  Similar to the memory usage display.

**Comment by jtpio** [comment]
@KahThong this would have to be added the classic notebook extension here: https://github.com/jupyter-server/jupyter-resource-usage/blob/c7d5970ac912fc5ed71280ab2eab04be686187bd/jupyter_resource_usage/static/main.js#L6
