### ISSUE TITLE
Drop the deprecated /metrics endpoint

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter-resource-usage#75]
Originally posted by @manics in https://github.com/jupyter-server/jupyter-resource-usage/issues/73#issuecomment-734259956

> If you're renaming the package this might be a good opportunity to make any breaking changes? e.g. following up from #68 /metrics could be completely removed instead of just deprecated?

We should consider doing this for the next major release, so adding to the 0.5.0 milestone.

**Comment by yuvipanda** [comment]
YESSS. LET US KILL IT.

Killing it also would mean we can run nbresuse and jupyter-resource-usage side by side.
