### ISSUE TITLE
Add docs to configure with Jupyter Server

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter-resource-usage#79]
For now the readme mentions configuring `ResourceDisplay` with `c.NotebookApp.ResourceUseDisplay`.

We should also document configuring `c.ServerApp.ResourceUseDisplay` in `PREFIX/etc/jupyter/jupyter_server_config.py` when using Jupyter Server directly (for example if only JupyterLab is installed).

**Comment by hMED22** [comment]
Why not use `c.ResourceUseDisplay.track_cpu_percent = True` instead, its how I understand traitlets configurable works, I don't get why `c.NotebookApp.ResourceUseDisplay` is working.

`c.ResourceUseDisplay.track_cpu_percent = True` worked for me in both `jupyter_server_config.py` and `jupyter_notebook_config.py` with Jupyterlab3.

**Comment by jtpio** [comment]
Thanks @hMED22.

Would you like to open a PR to document this?

**Comment by hMED22** [comment]
Sure, will do.
