### ISSUE TITLE
Resource usage of current kernel?

### ISSUE THREAD

**Issue by Hoeze** [jupyter-server/jupyter-resource-usage#88]
Hi, I just installed this extension and I already don't want to miss it any more.

Would it be possible to add a second metric that shows only the memory usage of the currently active kernel?
This would be very useful to find out how much RAM I should request for running a certain notebook.

**Comment by jtpio** [comment]
Thanks @Hoeze.

Indeed this would be really useful. There has been some discussions about this feature in https://github.com/jupyter-server/jupyter-resource-usage/issues/31. Maybe we could move the conversation there?

**Comment by Hoeze** [comment]
I see, thanks @jtpio. I'm closing this issue then :)
