### ISSUE TITLE
Clarify notebook/jupyter_server usage

### ISSUE THREAD

**Issue by fcollonval** [jupyter-server/jupyter-resource-usage#92]
## Description

The code is not a full valid `jupyter_server` extension as it is based on `notebook` handler:

https://github.com/jupyter-server/jupyter-resource-usage/blob/77ef2341efdee67a1457b6c6a0de5e001ca4c3aa/jupyter_resource_usage/api.py#L5

Dependency needs update:

https://github.com/jupyter-server/jupyter-resource-usage/blob/77ef2341efdee67a1457b6c6a0de5e001ca4c3aa/setup.py#L78

The backport entrypoint is missing: 
```
_load_jupyter_server_extension = load_jupyter_server_extension
```

## Expected behavior

The extension is fully using `jupyter_server`.

## Context

The mix-up was seen following that issue: https://github.com/jupyter-server/jupyter_server/issues/488

After changing the parameter to `c.Spawner.cmd = ["jupyter-labhub"]`, the warning is emitted only for this handler:

```
python3.7/site-packages/notebook/base/handlers.py:131: RuntimeWarning: Expected to see HubAuthenticatedHandler in <class 'jupyter_resource_usage.api.ApiHandler'>.mro()
```

**Comment by jtpio** [comment]
Thanks @fcollonval for the report.

This might also explain some of the issues folks have been having in https://github.com/jupyter-server/jupyter-resource-usage/issues/91.

Please don't hesitate to send a PR over if you have something to make this better (even as a draft). Thanks!
